title: Thunkable ✕ Templates
baseurl: /
permalink: /:title/
color_scheme: light
accent_color: blue
header:
  title: Thunkable X Templates
  has_nav: true
  logo_img: ""
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: /posts/:title/
footer:
  content: Made with ❤️️ for Thunkers.
  links:
    - new_window: true
      text: Thunkable
      url: https://thunkable.com
  has_social: false
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
